# Generated by Django 4.2.12 on 2024-07-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_toilet_latitude_toilet_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='toilet',
            name='name',
            field=models.CharField(default='Unknown Location', max_length=100),
        ),
    ]
