# Generated by Django 4.2.12 on 2024-07-22 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_toilet_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toilet',
            name='toilet_id',
        ),
    ]
