# Generated by Django 4.2.12 on 2024-07-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_toilet_toilet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='toilet',
            name='sexes',
            field=models.CharField(default='Male/Female', max_length=30),
        ),
    ]
